"use strict";
const { redactValue } = require("./evidence");
const ADAPTER_REGISTRY_SCHEMA_VERSION = 1;
const ADAPTER_KINDS = Object.freeze(["filesystem", "shell", "repository", "test_runner", "package_manager", "local_http", "process_health", "browser", "api", "database_read_only", "database_mutation", "deployment", "publish", "scm"]);
const POLICIES = new Set(["safe", "supervised", "authorized_external", "unrestricted", "unrestricted_general", "always_blocked"]);
const BAD_KEYS = new Set(["__proto__", "prototype", "constructor"]);
const SENSITIVE = /token|secret|password|credential|api[_-]?key|authorization|private[_ -]?key/i;
const FIELDS = new Set(["schema_version", "name", "capabilities", "input_schema", "output_schema", "side_effects", "reversible", "rollback_support", "verification_support", "environment_requirements", "execution_policy", "production", "enabled", "executor"]);
const CAPABILITIES = Object.freeze({ filesystem: ["read", "workspace_write"], shell: ["shell_execute"], repository: ["read", "inspect", "workspace_write"], test_runner: ["test_execute", "verify"], package_manager: ["package_execute", "workspace_write"], local_http: ["local_http"], process_health: ["process_health"], browser: ["browser"], api: ["external_call"], database_read_only: ["database_read"], database_mutation: ["database_mutation"], deployment: ["deploy"], publish: ["publish"], scm: ["scm_write"] });
const MUTATING = new Set(["filesystem", "repository", "package_manager", "database_mutation", "deployment", "publish", "scm"]);
function plain(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const proto = Object.getPrototypeOf(value); return proto === Object.prototype || proto === null; }
function list(value) { return Array.isArray(value) ? value : []; }
function issue(path, code) { return { path, code }; }
function badKeys(value) { if (Array.isArray(value)) return value.some(badKeys); if (!value || typeof value !== "object") return false; if (!plain(value)) return true; return Object.entries(value).some(([key, child]) => BAD_KEYS.has(key) || badKeys(child)); }
function validateSchema(value, schema, path = "$", errors = []) { if (!plain(schema)) return [issue(path, "INVALID_SCHEMA")]; const type = schema.type; const validType = !type || (type === "object" ? plain(value) : type === "array" ? Array.isArray(value) : type === "null" ? value === null : typeof value === type); if (!validType) errors.push(issue(path, "SCHEMA_TYPE")); if (type === "object" && plain(value)) { for (const key of list(schema.required)) if (!(key in value)) errors.push(issue(`${path}.${key}`, "SCHEMA_REQUIRED")); for (const [key, child] of Object.entries(value)) { if (BAD_KEYS.has(key)) errors.push(issue(`${path}.${key}`, "DANGEROUS_FIELD")); else if (schema.properties?.[key]) validateSchema(child, schema.properties[key], `${path}.${key}`, errors); else if (schema.additionalProperties === false) errors.push(issue(`${path}.${key}`, "SCHEMA_UNKNOWN")); } } if (type === "array" && Array.isArray(value) && schema.items) value.forEach((item, index) => validateSchema(item, schema.items, `${path}[${index}]`, errors)); return errors; }
function validateAdapterSchema(schema, path = "schema") { const errors = !plain(schema) || !["object", "array", "string", "number", "boolean", "null"].includes(schema.type) ? [issue(`${path}.type`, "INVALID_SCHEMA")] : []; if (badKeys(schema)) errors.push(issue(path, "DANGEROUS_FIELD")); return { valid: errors.length === 0, errors }; }
function descriptor(input = {}) { return { schema_version: ADAPTER_REGISTRY_SCHEMA_VERSION, name: input.name, capabilities: list(input.capabilities), input_schema: input.input_schema || { type: "object", additionalProperties: true }, output_schema: input.output_schema || { type: "object", required: ["success"], properties: { success: { type: "boolean" } }, additionalProperties: true }, side_effects: list(input.side_effects), reversible: input.reversible === true, rollback_support: input.rollback_support === true, verification_support: input.verification_support === true, environment_requirements: plain(input.environment_requirements) ? input.environment_requirements : {}, execution_policy: input.execution_policy || "safe", production: input.production === true, enabled: input.enabled !== false, executor: input.executor }; }
function validateAdapterDescriptor(value) { const errors = []; if (!plain(value)) return { valid: false, errors: [issue("$", "INVALID_OBJECT")] }; for (const key of Object.keys(value)) if (!FIELDS.has(key)) errors.push(issue(key, BAD_KEYS.has(key) ? "DANGEROUS_FIELD" : "UNKNOWN_FIELD")); if (!ADAPTER_KINDS.includes(value.name)) errors.push(issue("name", "INVALID_NAME")); if (!Array.isArray(value.capabilities)) errors.push(issue("capabilities", "INVALID_LIST")); for (const field of ["input_schema", "output_schema"]) errors.push(...validateAdapterSchema(value[field], field).errors); if (!Array.isArray(value.side_effects)) errors.push(issue("side_effects", "INVALID_LIST")); for (const field of ["reversible", "rollback_support", "verification_support", "production", "enabled"]) if (typeof value[field] !== "boolean") errors.push(issue(field, "INVALID_BOOLEAN")); if (!plain(value.environment_requirements)) errors.push(issue("environment_requirements", "INVALID_OBJECT")); if (!POLICIES.has(value.execution_policy)) errors.push(issue("execution_policy", "INVALID_POLICY")); if (value.executor !== undefined && typeof value.executor !== "function") errors.push(issue("executor", "INVALID_EXECUTOR")); if (badKeys(value)) errors.push(issue("$", "DANGEROUS_FIELD")); return { valid: errors.length === 0, errors }; }
function builtinAdapters() { return ADAPTER_KINDS.map(name => descriptor({ name, capabilities: CAPABILITIES[name], side_effects: MUTATING.has(name) ? [name] : [], reversible: MUTATING.has(name), rollback_support: MUTATING.has(name), verification_support: true, environment_requirements: { adapter_injected: true }, execution_policy: ["api", "database_mutation", "deployment", "publish", "scm"].includes(name) ? "authorized_external" : "safe", enabled: true })); }

function redact(value, key = "") { if (SENSITIVE.test(key) || BAD_KEYS.has(key)) return "[REDACTED]"; if (Array.isArray(value)) return value.map(item => redact(item)); if (plain(value)) return Object.fromEntries(Object.entries(value).map(([name, child]) => [name, redact(child, name)])); return typeof value === "string" ? value.replace(/Bearer\s+[^\s]+/gi, "Bearer [REDACTED]") : value; }

function registerAdapter(registry, input) { const value = descriptor(input); const validation = validateAdapterDescriptor(value); if (!(registry instanceof Map) || !validation.valid) throw new TypeError(`Invalid adapter: ${validation.errors.map(error => error.path).join(",")}`); registry.set(value.name, value); return value; }
function createAdapterRegistry(inputs = []) { const registry = new Map(); for (const item of [...builtinAdapters(), ...list(inputs)]) registerAdapter(registry, item); return registry; }
function getAdapter(registry, name) { return registry instanceof Map ? registry.get(name) || null : null; }
function publicDescriptor(adapter) { const copy = { ...adapter }; delete copy.executor; return redact(copy); }
function discoverAdapters(registry = createAdapterRegistry(), requirements = {}) { const requested = new Set(list(requirements.capabilities)); return [...registry.values()].filter(adapter => adapter.enabled && (!requested.size || adapter.capabilities.some(capability => requested.has(capability)))).map(publicDescriptor); }
function productionGate(adapter, options) { if (!adapter.production) return null; if (options.production_adapter_opt_in !== true) return { status: "production_disabled", code: "PRODUCTION_ADAPTER_DISABLED" }; if (options.audit_persisted !== true || options.integrity_preflight !== true) return { status: "production_disabled", code: "PRODUCTION_AUDIT_REQUIRED" }; return null; }

function finalize(adapter, output) { const value = plain(output) ? redactValue(output) : output; const errors = validateSchema(value, adapter.output_schema); if (errors.length) return { success: false, completed: false, status: "invalid_output", code: "ADAPTER_OUTPUT_INVALID", adapter: adapter.name, errors }; const evidence = value?.verifier_evidence || value?.evidence; const verified = value?.success === true && (value.verified === true || list(evidence).some(item => item?.valid === true && item?.executed === true)); return { ...value, adapter: adapter.name, completed: verified, status: value.success === true ? (verified ? "completed" : "verification_required") : "failed", verification_required: value.success === true && !verified, rollback_support: adapter.rollback_support }; }
function executeAdapter(registry, name, input = {}, options = {}) { const adapter = getAdapter(registry, name); if (!adapter) return { success: false, completed: false, status: "adapter_not_found", code: "ADAPTER_NOT_FOUND", adapter: name }; const inputErrors = validateSchema(input, adapter.input_schema); if (inputErrors.length) return { success: false, completed: false, status: "invalid_input", code: "ADAPTER_INPUT_INVALID", adapter: name, errors: inputErrors }; const missing = adapter.capabilities.filter(capability => !list(options.capabilities).includes(capability)); if (missing.length) return { success: false, completed: false, status: "capability_mismatch", code: "ADAPTER_CAPABILITY_MISMATCH", adapter: name, missing_capabilities: missing }; const gate = productionGate(adapter, options); if (gate) return { success: false, completed: false, adapter: name, ...gate }; if (adapter.execution_policy === "always_blocked") return { success: false, completed: false, status: "blocked", code: "ALWAYS_BLOCKED", adapter: name }; if (!adapter.enabled) return { success: false, completed: false, status: "adapter_disabled", code: "ADAPTER_DISABLED", adapter: name }; if (typeof adapter.executor !== "function") return { success: false, completed: false, status: "adapter_unavailable", code: "ADAPTER_NOT_INJECTED", adapter: name }; try { const result = adapter.executor(input, { adapter: publicDescriptor(adapter), options: redact(options) }); return result?.then ? result.then(value => finalize(adapter, value)).catch(error => ({ success: false, completed: false, status: "adapter_failed", code: "ADAPTER_EXECUTION_FAILED", adapter: name, error: redact({ message: error.message }) })) : finalize(adapter, result); } catch (error) { return { success: false, completed: false, status: "adapter_failed", code: "ADAPTER_EXECUTION_FAILED", adapter: name, error: redact({ message: error.message }) }; } }
function adapterFailureToBlockerInput(result, context = {}) { const category = result?.code === "ADAPTER_CAPABILITY_MISMATCH" ? "missing_capability" : result?.code === "ADAPTER_INPUT_INVALID" ? "scope_violation" : result?.code?.startsWith("PRODUCTION_") ? "permission_blocked" : result?.status === "verification_required" ? "insufficient_evidence" : "environment_failure"; return redactValue({ category, stage: "adapter", cause: result?.code || "adapter failure", affected_step: context.step_id || null, evidence: context.evidence || [], retryable: category !== "permission_blocked", requires_permission: category === "permission_blocked", alternatives: [{ alternative_id: "adapter-local-fallback", description: "Use an injected local or mock adapter", source: "local_fallback", side_effects: [], reversible: true, approval_required: false, applicable: true }, { alternative_id: "adapter-escalate", description: "Escalate with adapter evidence", source: "user_decision", side_effects: [], reversible: true, approval_required: true, applicable: true }] }); }
function adapterCapabilitiesForPlan(requirements = [], registry = createAdapterRegistry()) { const requested = new Set(list(requirements)); return discoverAdapters(registry, { capabilities: [...requested] }).map(item => ({ name: item.name, capabilities: item.capabilities, side_effects: item.side_effects, verification_support: item.verification_support, execution_policy: item.execution_policy })); }
const discoverAdapterCapabilities = adapterCapabilitiesForPlan;
module.exports = { ADAPTER_REGISTRY_SCHEMA_VERSION, ADAPTER_KINDS, validateSchema, validateAdapterSchema, validateAdapterDescriptor, descriptor, builtinAdapters, createAdapterRegistry, registerAdapter, getAdapter, discoverAdapters, executeAdapter, adapterFailureToBlockerInput, adapterCapabilitiesForPlan, discoverAdapterCapabilities, publicDescriptor };
