"use strict";
const crypto = require("crypto");
const { createGoalPlan, validateGoalPlan, detectSideEffects } = require("./plan");
const { redactValue } = require("./evidence");
const { createHypothesis, createAssumption } = require("./hypothesis");
const { DOMAIN_STATUSES } = require("./supported_domains");
const PLAN_STATUSES = Object.freeze(["draft", "provisional", "ready", "executing", "replanning", "completed", "blocked", "escalated", "invalidated"]);
const BAD_KEYS = new Set(["__proto__", "prototype", "constructor"]);
const ALWAYS_BLOCKED = /private\s*key|credential\s*(?:value|secret)|password\s*(?:logging|exposure)|token\s*(?:logging|exposure)|approval\s*bypass|verifier\s*tamper|force\s*push|drop\s+database|destroy\s+workspace/i;
const PATH_PATTERN = /(?:^|\s)((?:[A-Za-z0-9._-]+[\\/])+[A-Za-z0-9._-]+)/g;
function plain(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const proto = Object.getPrototypeOf(value); return proto === Object.prototype || proto === null; }
function array(value) { return Array.isArray(value) ? value : []; }
function clean(value) { return typeof value === "string" ? value.replace(/\\/g, "/").replace(/\s+/g, " ").trim() : ""; }
function normalizePath(value) { return clean(value).replace(/^\.\//, ""); }
function paths(value) { return [...String(value || "").matchAll(PATH_PATTERN)].map(match => normalizePath(match[1])); }
function stableId(prefix, value) { return `${prefix}_${crypto.createHash("sha256").update(JSON.stringify(redactValue(value))).digest("hex").slice(0, 16)}`; }
function hasBadKey(value) { if (Array.isArray(value)) return value.some(hasBadKey); if (!value || typeof value !== "object") return false; if (!plain(value)) return true; return Object.entries(value).some(([key, child]) => BAD_KEYS.has(key) || hasBadKey(child)); }
function scopeOf(context = {}) { const odd = context.repository_context?.repository_odd || context.repository_odd || context.scope_boundary || {}; return { allowed_paths: array(odd.allowed_paths), blocked_paths: array(odd.blocked_paths), protected_paths: array(odd.protected_paths), allow_external: odd.allow_external === true }; }
function withinScope(file, scope) { const item = normalizePath(file); if (!item || item.startsWith("/") || /^[A-Za-z]:\//.test(item) || item.split("/").includes("..")) return false; if (scope.blocked_paths.some(prefix => item === normalizePath(prefix) || item.startsWith(`${normalizePath(prefix)}/`))) return false; if (scope.protected_paths.some(prefix => item === normalizePath(prefix) || item.startsWith(`${normalizePath(prefix)}/`))) return false; return scope.allowed_paths.length === 0 || scope.allowed_paths.some(prefix => item === normalizePath(prefix) || item.startsWith(`${normalizePath(prefix)}/`)); }
function modeOf(intent, context) { return context.execution_policy?.mode || context.mode || intent.execution_policy?.mode || "safe"; }
function onlyGoal(context, intent) { return context.only_goal === true || /\b(only|just|goal\s+only)\b|목표만/i.test(`${intent.raw_objective || ""} ${context.objective || ""}`); }
function relatedRequested(context, intent) { return context.related_work === true || /알아서|필요한 것까지|related work|everything needed|end[- ]to[- ]end/i.test(`${intent.raw_objective || ""} ${context.objective || ""}`); }
function step(id, description, options = {}) { return { id, description, source: "inferred", purpose: options.purpose || description, required: options.required !== false, depends_on: array(options.depends_on), target_criteria: array(options.target_criteria), risk: options.risk || "low", side_effects: array(options.side_effects), verification: options.verification || { type: "repository_check" }, status: options.status || "proposed", rationale: options.rationale || "", execution_policy: options.execution_policy || "safe", inputs: array(options.inputs), expected_outputs: array(options.expected_outputs), rollback_plan: options.rollback_plan || "No mutation is performed without policy and evidence gates", requested_capabilities: array(options.requested_capabilities), confidence: options.confidence ?? 0 }; }
function uniqueSteps(steps) { const seen = new Set(); return steps.filter(item => { const key = `${item.id}|${item.description.toLowerCase()}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
function cycleErrors(steps) { const ids = new Set(steps.map(item => item.id)); const errors = []; const state = new Map(); function visit(id, chain = []) { if (!ids.has(id)) { errors.push(`missing dependency: ${id}`); return; } if (state.get(id) === "active") { errors.push(`cyclic dependency: ${[...chain, id].join(" -> ")}`); return; } if (state.get(id) === "done") return; state.set(id, "active"); const current = steps.find(item => item.id === id); for (const dependency of current.depends_on) visit(dependency, [...chain, id]); state.set(id, "done"); } for (const item of steps) visit(item.id); return [...new Set(errors)]; }

function generalSteps(intent, context, criteria, scope) {
  const objective = clean(intent.normalized_objective || intent.raw_objective); const namedPaths = array(intent.requested_scope?.paths).concat(paths(objective)); const safePaths = [...new Set(namedPaths.map(normalizePath).filter(Boolean))]; const hasFileScope = safePaths.length > 0; const result = [];
  result.push(step("general-observe", "Observe the authorized workspace, tools, and current state before acting", { purpose: "Establish facts for planning", target_criteria: criteria, verification: { type: "repository_observation", paths: safePaths }, expected_outputs: ["workspace_observation"], rationale: "Open-world goals require current environment facts", confidence: 0.86, requested_capabilities: ["read", "inspect", "verify"] }));
  if (hasFileScope) result.push(step("general-scope-check", `Confirm the requested scope for ${safePaths.join(", ")}`, { purpose: "Prevent unrelated changes", depends_on: ["general-observe"], target_criteria: criteria, verification: { type: "scope_check", paths: safePaths }, expected_outputs: ["authorized_scope"], rationale: "Explicit paths are the strongest scope signal", confidence: 0.82, requested_capabilities: ["read", "inspect", "verify"] }));
  result.push(step("general-local-work", `Perform the lowest-risk local work needed to advance: ${objective || "the provisional objective"}`, { purpose: "Advance the requested outcome", depends_on: [hasFileScope ? "general-scope-check" : "general-observe"], target_criteria: criteria, side_effects: hasFileScope ? ["file_change"] : [], risk: hasFileScope ? "medium" : "low", verification: { type: "repository_check", paths: safePaths }, expected_outputs: ["local_result"], rationale: "Provisional action remains within ODD", confidence: 0.58, requested_capabilities: hasFileScope ? ["workspace_write", "verify"] : ["read", "inspect", "verify"] }));
  result.push(step("general-verify", "Run deterministic checks and record evidence for provisional criteria", { purpose: "Verify outcome without self-report", depends_on: ["general-observe"], target_criteria: criteria, verification: { type: "repository_check", checks: array(context.verification_checks).length ? context.verification_checks : ["git_status", "changed_files"] }, expected_outputs: ["verification_evidence"], rationale: "Completion requires executed evidence", confidence: 0.72, requested_capabilities: ["read", "inspect", "verify"] }));
  return { steps: result, paths: safePaths };
}
function provisionalCriteria(intent) { const objective = clean(intent.normalized_objective || intent.raw_objective) || "the requested goal"; return [{ id: "provisional-outcome", description: `The observable outcome for ${objective} is identified and verified`, required: true, provisional: true, source: "inferred", confidence: 0.42, rationale: "No explicit success criterion was supplied; this remains provisional" }]; }
function candidateVerifier(_intent = null) { return [{ id: "provisional-observation", type: "custom", description: "Observe workspace state and deterministic checks related to the goal", config: { kind: "open_world_observation" }, provisional: true, confidence: 0.45, rationale: "Verifier is a candidate until execution reveals a concrete check" }]; }
function expandGoalGeneral(intent, context = {}) {
  const value = redactValue(intent || {}); const scope = scopeOf(context); const mode = modeOf(value, context); const only = onlyGoal(context, value); const related = relatedRequested(context, value); const planningTrace = [trace("intent_received", { goal_type: value.goal_type || "unknown", mode }, 0.7)];
  if (!plain(value) || hasBadKey(value)) return { status: "blocked", goal_plan: null, inferred_steps: [], optional_steps: [], dependencies: [], hypotheses: [], assumptions: [], candidate_criteria: [], candidate_verifiers: [], missing_information: ["Invalid or dangerous intent input"], out_of_scope_candidates: [], confidence: 0, requires_user_confirmation: true, planning_trace: [trace("input_rejected", "dangerous or non-plain intent", 0)] };
  if (!DOMAIN_STATUSES.includes(value.support_status || "clarification_required") || value.support_status === "unsupported") return { status: "blocked", goal_plan: null, inferred_steps: [], optional_steps: [], dependencies: [], hypotheses: [], assumptions: [], candidate_criteria: [], candidate_verifiers: candidateVerifier(value), missing_information: ["Goal is outside the supported general autonomy domain", ...(array(value.support_reasons))], out_of_scope_candidates: array(value.requested_scope?.paths).map(file => ({ path: file, status: "not_added", reason: "unsupported_domain" })), confidence: 0, requires_user_confirmation: true, support_status: "unsupported", supported_domain: value.supported_domain || "unknown", execution_boundary: "unsupported", planning_trace: planningTrace.concat(trace("unsupported_domain", { domain: value.supported_domain || "unknown", reasons: value.support_reasons || [] }, 0)) };
  const candidateCriteria = Array.isArray(value.candidate_success_criteria) && value.candidate_success_criteria.length ? value.candidate_success_criteria.map(item => ({ ...redactValue(item), provisional: item.provisional === true || value.interpretation_status !== "interpreted" })) : provisionalCriteria(value); const planCriteria = candidateCriteria.map(item => ({ id: item.id || "provisional-outcome", description: item.description || item.text || "Observable outcome is verified", required: item.required !== false })); const criteriaIds = planCriteria.map(item => item.id).filter(Boolean); const generated = generalSteps(value, context, criteriaIds, scope); const violations = generated.paths.filter(item => !withinScope(item, scope));
  if (violations.length || ALWAYS_BLOCKED.test(`${value.normalized_objective || ""} ${generated.steps.map(item => item.description).join(" ")}`)) return { status: "blocked", goal_plan: null, inferred_steps: [], optional_steps: [], dependencies: [], hypotheses: [], assumptions: [], candidate_criteria: candidateCriteria, candidate_verifiers: candidateVerifier(value), missing_information: violations.length ? violations.map(item => `Path outside workspace ODD: ${item}`) : ["Always-blocked integrity operation detected"], out_of_scope_candidates: violations.map(path => ({ path, status: "not_added", reason: "workspace_odd_scope" })), confidence: 0, requires_user_confirmation: true, planning_trace: planningTrace.concat(trace("safety_rejection", { violations }, 0)) };
  let steps = uniqueSteps(generated.steps); const cycle = cycleErrors(steps); if (cycle.length) return { status: "blocked", goal_plan: null, inferred_steps: [], optional_steps: [], dependencies: [], hypotheses: [], assumptions: [], candidate_criteria: candidateCriteria, candidate_verifiers: candidateVerifier(value), missing_information: cycle, out_of_scope_candidates: [], confidence: 0, requires_user_confirmation: true, planning_trace: planningTrace.concat(trace("cycle_rejected", cycle, 0)) };

function trace(event, detail, confidence = 0.5) { return { trace_id: stableId("trace", { event, detail }), event, detail: redactValue(detail), confidence, timestamp: new Date().toISOString() }; }

  if (only) { steps = steps.map(item => item.id === "general-local-work" ? { ...item, required: true } : item); planningTrace.push(trace("only_goal_applied", "Optional follow-up work is not added", 0.9)); }
  else if (related && mode === "unrestricted_general") { steps = steps.map(item => item.confidence >= 0.7 ? { ...item, required: true, promotion_rationale: "low-risk related work requested by user" } : { ...item, required: false }); planningTrace.push(trace("related_work_promoted", "Low-risk related steps promoted", 0.72)); }
  else steps = steps.map(item => item.id === "general-observe" || item.id === "general-verify" ? item : { ...item, required: false, status: "deferred" });
  const inferredSteps = steps.filter(item => item.required); const optionalSteps = steps.filter(item => !item.required); const capabilities = [...new Set(inferredSteps.flatMap(item => item.requested_capabilities))]; const hasMutation = inferredSteps.some(item => detectSideEffects(item).includes("file_change")); const needsConfirmation = mode !== "unrestricted_general" || candidateCriteria.some(item => item.provisional) || inferredSteps.some(item => item.risk !== "low") || value.interpretation_status !== "interpreted";
  const hypotheses = candidateCriteria.map(item => createHypothesis({ statement: item.description || item.text, basis: item.rationale || "candidate criterion", source: item.source === "explicit" ? "explicit" : "inferred", confidence: item.confidence || 0.4, impact_if_wrong: item.provisional ? "high" : "medium", reversibility: "reversible", requires_confirmation: item.provisional === true, related_criteria: [item.id], status: "proposed" })); const assumptions = [createAssumption({ statement: "The authorized workspace and available verifier remain usable", source: "inferred", confidence: 0.7, risk_level: hasMutation ? "medium" : "low", affects_steps: inferredSteps.map(item => item.id), invalidation_signals: ["workspace boundary changed", "verifier unavailable"] })];
  const planInput = { objective: value.normalized_objective || value.raw_objective || "Provisional general goal", explicit_steps: [], inferred_steps: inferredSteps, dependencies: inferredSteps.flatMap(item => item.depends_on.length ? [{ step_id: item.id, depends_on: item.depends_on }] : []), success_criteria: planCriteria.length ? planCriteria : [{ id: "provisional-outcome", description: "Observable outcome is verified", required: true }], scope_boundary: scope, risk_level: inferredSteps.some(item => item.risk === "critical") ? "critical" : inferredSteps.some(item => item.risk === "high") ? "high" : inferredSteps.some(item => item.risk === "medium") ? "medium" : "low", approval_requirements: hasMutation ? ["file_change"] : [], assumptions: assumptions.map(item => item.statement), execution_policy: "safe", requested_capabilities: capabilities, granted_capabilities: capabilities.filter(item => ["read", "inspect", "verify"].includes(item)), denied_capabilities: capabilities.filter(item => !["read", "inspect", "verify"].includes(item)), requires_explicit_confirmation: needsConfirmation, always_blocked_actions: [] };
  const planCandidate = createGoalPlan(planInput); const planValidation = validateGoalPlan(planCandidate); const goalPlan = planValidation.valid ? planCandidate : null; if (!goalPlan) planningTrace.push(trace("goal_plan_validation_failed", planValidation.errors, 0));

  const confidence = Math.min(0.72, Math.max(0, value.confidence || 0.42)); const status = goalPlan ? (candidateCriteria.some(item => item.provisional) ? "provisional" : confidence >= 0.65 ? "ready" : "provisional") : "blocked";
  planningTrace.push(trace("plan_created", { status, steps: steps.map(item => item.id), only_goal: only, related_work: related }, confidence));
  return { status, goal_plan: goalPlan, inferred_steps: inferredSteps, optional_steps: optionalSteps, dependencies: planInput.dependencies, hypotheses, assumptions, candidate_criteria: candidateCriteria, candidate_verifiers: candidateVerifier(), missing_information: array(value.missing_information).map(item => typeof item === "string" ? item : item.text), out_of_scope_candidates: [], confidence, requires_user_confirmation: needsConfirmation || !goalPlan, planning_trace: planningTrace, requested_capabilities: capabilities, granted_capabilities: planInput.granted_capabilities, denied_capabilities: planInput.denied_capabilities };
}
module.exports = { PLAN_STATUSES, expandGoalGeneral, withinScope, cycleErrors, onlyGoal, relatedRequested };
