"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const { interpretNaturalLanguageGoal } = require("./intent");
const { runGeneralGoalLoop, nextReadyStep } = require("./general_loop");
function goal(text = "Fix the bug in src/parser.js") { return interpretNaturalLanguageGoal(text); }
function plan() { return { plan_version: 1, status: "ready", steps: [{ id: "observe", description: "Observe", depends_on: [], target_criteria: ["goal"], status: "proposed" }, { id: "work", description: "Work", depends_on: ["observe"], target_criteria: ["goal"], status: "proposed" }, { id: "verify", description: "Verify", depends_on: ["work"], target_criteria: ["goal"], status: "proposed" }] }; }
test("runs a general natural-language goal through observe plan execute verify", async () => { const actions = []; const result = await runGeneralGoalLoop(goal(), { max_cycles: 4, plan: async () => ({ plan: plan(), status: "ready" }), observe: async () => ({ repository: { dirty: false } }), execute: async step => { actions.push(step.id); return { status: "passed", executed: true, verification: { status: "passed", valid: true, executed: true, evidence: { valid: true, executed: true } } }; }, verify: async () => ({ completed: true, evidence: [{ evidence_id: "final", valid: true, executed: true }] }) }); assert.equal(result.state, "completed"); assert.ok(actions.length > 0); assert.ok(result.action_history.length >= actions.length); });
test("uses dependency order and does not repeat completed steps", () => { const p = plan(); const completed = new Set(["observe"]); assert.equal(nextReadyStep(p, completed, new Set()).id, "work"); assert.equal(nextReadyStep(p, new Set(["observe", "work"]), new Set()).id, "verify"); });
test("blocks unrestricted_general without explicit activation", async () => { const result = await runGeneralGoalLoop(goal(), { mode: "unrestricted_general" }); assert.equal(result.state, "blocked"); assert.match(result.final_reason, /explicit activation/i); });
test("pauses with a safe checkpoint", async () => { const result = await runGeneralGoalLoop(goal(), { pause: true }); assert.equal(result.state, "paused"); assert.equal(result.checkpoints.length, 1); assert.ok(result.checkpoints[0].checkpoint_id); });
test("handles blocker, alternative replan, and multi-cycle completion", async () => { let attempts = 0; const result = await runGeneralGoalLoop(goal(), { max_cycles: 5, plan: async () => ({ plan: plan(), status: "ready" }), observe: async () => ({}), execute: async step => { attempts += 1; return attempts === 1 ? { status: "failed", executed: true, reason: "blocked", verification: { status: "failed", valid: false, executed: true, evidence: { valid: false, executed: true } } } : { status: "passed", executed: true, verification: { status: "passed", valid: true, executed: true, evidence: { valid: true, executed: true } } }; }, replan: async previous => ({ ...previous, plan_version: previous.plan_version + 1, steps: previous.steps.map(step => ({ ...step, status: "proposed" })) }), verify: async () => attempts > 1 ? { completed: true } : { completed: false } }); assert.ok(result.blocker_reports.length > 0); assert.ok(result.replan_history.length > 0); assert.ok(["completed", "escalated", "stagnated"].includes(result.state)); });
test("prevents false completion from model self-report and unknown verification", async () => { const result = await runGeneralGoalLoop(goal(), { max_cycles: 1, plan: async () => ({ plan: plan(), status: "ready" }), execute: async () => ({ status: "unknown", executed: true, verification: { status: "unknown", valid: false, evidence: { valid: false, executed: true } } }), verify: async () => ({ completed: true, model_self_report: true, results: [{ status: "passed", valid: true, evidence: { valid: true, executed: true } }] }) }); assert.notEqual(result.state, "completed"); });
test("keeps source/runtime loop implementation in parity", () => { const read = file => fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n"); assert.equal(read(path.join(__dirname, "general_loop.js")), read(path.join(__dirname, "..", "..", "extension", "runtime", "src", "goal", "general_loop.js"))); });
