"use strict";

const crypto = require("crypto");
const { redactValue } = require("./evidence");
const { createHypothesis, createAssumption } = require("./hypothesis");
const { PLAN_STATUSES } = require("./expansion_general");

const PLANNER_SCHEMA_VERSION = 1;
const BAD_KEYS = new Set(["__proto__", "prototype", "constructor"]);
const PLAN_FIELDS = new Set(["schema_version", "plan_id", "plan_version", "objective", "subgoals", "steps", "dependencies", "hypotheses", "assumptions", "replanning_reason", "discarded_steps", "new_steps", "preserved_steps", "confidence", "next_step", "status", "planning_trace", "rejected_patch_signatures"]);
function plain(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const proto = Object.getPrototypeOf(value); return proto === Object.prototype || proto === null; }
function array(value) { return Array.isArray(value) ? value : []; }
function text(value) { return typeof value === "string" && value.trim() !== ""; }
function clean(value) { return typeof value === "string" ? value.replace(/\s+/g, " ").trim() : ""; }
function stableId(prefix, value) { return `${prefix}_${crypto.createHash("sha256").update(JSON.stringify(redactValue(value))).digest("hex").slice(0, 16)}`; }
function hasBadKey(value) { if (Array.isArray(value)) return value.some(hasBadKey); if (!value || typeof value !== "object") return false; if (!plain(value)) return true; return Object.entries(value).some(([key, child]) => BAD_KEYS.has(key) || hasBadKey(child)); }
function issue(path, code, message) { return { path, code, message }; }
function trace(event, detail, evidenceIds = []) { return { trace_id: stableId("planner-trace", { event, detail, evidenceIds }), event, detail: redactValue(detail), evidence_ids: array(evidenceIds), rationale: clean(typeof detail === "string" ? detail : event), timestamp: new Date().toISOString() }; }
function normalizeStep(step = {}, index = 0) { const id = step.id || step.step_id || `general-step-${index + 1}`; return redactValue({ ...step, id, step_id: id, depends_on: array(step.depends_on), required: step.required !== false, status: step.status || "proposed", confidence: typeof step.confidence === "number" ? step.confidence : 0.5, source: step.source || "inferred" }); }
function stepKey(step) { return `${step.id}|${clean(step.description || step.purpose).toLowerCase()}`; }
function dedupeSteps(steps) { const seen = new Set(); return array(steps).map(normalizeStep).filter(step => { const key = stepKey(step); if (seen.has(key)) return false; seen.add(key); return true; }); }
function planId(intent, version = 1) { return stableId("general-plan", { intent_id: intent?.intent_id, objective: intent?.normalized_objective || intent?.raw_objective, version }); }
function buildInitialPlan(input = {}) {
  const intent = input.intent || {}; const steps = dedupeSteps(input.steps || input.inferred_steps); const objective = clean(intent.normalized_objective || intent.raw_objective || input.objective); const assumptions = array(input.assumptions).length ? array(input.assumptions) : [createAssumption({ statement: "The observed workspace and available tools remain usable", source: "inferred", confidence: 0.65, risk_level: "low", affects_steps: steps.map(step => step.id), invalidation_signals: ["tool unavailable", "workspace changed"] })]; const hypotheses = array(input.hypotheses).length ? array(input.hypotheses) : array(intent.candidate_success_criteria).map(item => createHypothesis({ statement: item.description || item.text || "The candidate outcome is observable", basis: item.rationale || "intent candidate", source: "inferred", confidence: item.confidence || 0.4, impact_if_wrong: "medium", reversibility: "reversible", related_criteria: item.id ? [item.id] : [], requires_confirmation: true })); const confidence = typeof input.confidence === "number" ? input.confidence : Math.min(0.8, Math.max(0.1, steps.reduce((sum, step) => sum + (step.confidence || 0.5), 0) / Math.max(1, steps.length))); const status = input.status || (confidence < 0.6 ? "provisional" : "ready"); const completed = new Set(array(input.completed_steps)); const next = steps.find(step => !completed.has(step.id) && step.status !== "completed" && step.status !== "skipped")?.id || null; return redactValue({ schema_version: PLANNER_SCHEMA_VERSION, plan_id: input.plan_id || planId(intent, input.plan_version || 1), plan_version: Number.isInteger(input.plan_version) && input.plan_version > 0 ? input.plan_version : 1, objective, subgoals: array(input.subgoals), steps, dependencies: array(input.dependencies), hypotheses, assumptions, replanning_reason: input.replanning_reason || null, discarded_steps: array(input.discarded_steps), new_steps: array(input.new_steps), preserved_steps: array(input.preserved_steps), confidence, next_step: next, status, planning_trace: array(input.planning_trace).concat(trace("plan_created", { objective, step_count: steps.length })), rejected_patch_signatures: array(input.rejected_patch_signatures) });
}

function validateGeneralPlan(value) {
  const errors = []; if (!plain(value)) return { valid: false, errors: [issue("$", "INVALID_OBJECT", "General plan must be a plain object")] }; for (const key of Object.keys(value)) if (!PLAN_FIELDS.has(key)) errors.push(issue(key, BAD_KEYS.has(key) ? "DANGEROUS_FIELD" : "UNKNOWN_FIELD", "Unknown general plan field")); if (hasBadKey(value)) errors.push(issue("$", "DANGEROUS_FIELD", "Dangerous nested key is not allowed")); if (value.schema_version !== PLANNER_SCHEMA_VERSION) errors.push(issue("schema_version", "INVALID_VERSION", "Unsupported planner schema version")); if (!/^general-plan_[A-Fa-f0-9]{16}$/.test(value.plan_id || "")) errors.push(issue("plan_id", "INVALID_ID", "Invalid general plan id")); if (!Number.isInteger(value.plan_version) || value.plan_version < 1) errors.push(issue("plan_version", "INVALID_VERSION", "plan_version must be positive")); if (!text(value.objective)) errors.push(issue("objective", "INVALID_STRING", "objective is required")); if (!PLAN_STATUSES.includes(value.status)) errors.push(issue("status", "INVALID_STATUS", "Invalid plan status")); if (!Array.isArray(value.steps)) errors.push(issue("steps", "INVALID_LIST", "steps must be an array")); else { const ids = new Set(); for (const [index, step] of value.steps.entries()) { if (!plain(step)) { errors.push(issue(`steps[${index}]`, "INVALID_OBJECT", "step must be an object")); continue; } if (!text(step.id) || ids.has(step.id)) errors.push(issue(`steps[${index}].id`, "INVALID_STEP_ID", "step ids must be unique and non-empty")); ids.add(step.id); if (!Array.isArray(step.depends_on)) errors.push(issue(`steps[${index}].depends_on`, "INVALID_DEPENDENCY", "depends_on must be an array")); } for (const step of value.steps) for (const dependency of array(step.depends_on)) if (!ids.has(dependency)) errors.push(issue(`steps.${step.id}.depends_on`, "UNKNOWN_STEP", `unknown dependency: ${dependency}`)); } if (!Array.isArray(value.dependencies) || !Array.isArray(value.hypotheses) || !Array.isArray(value.assumptions) || !Array.isArray(value.planning_trace)) errors.push(issue("plan", "INVALID_LIST", "plan collections must be arrays")); if (typeof value.confidence !== "number" || value.confidence < 0 || value.confidence > 1) errors.push(issue("confidence", "INVALID_CONFIDENCE", "confidence must be between 0 and 1")); return { valid: errors.length === 0, errors };
}
function assertValidGeneralPlan(value) { const result = validateGeneralPlan(value); if (!result.valid) throw new TypeError(`Invalid general plan: ${result.errors.map(item => item.path).join(",")}`); return value; }
function serializeGeneralPlan(value) { assertValidGeneralPlan(value); return JSON.stringify(redactValue(value)); }
function deserializeGeneralPlan(serialized) { if (typeof serialized !== "string" || !serialized.trim()) throw new TypeError("Serialized general plan must be non-empty"); return assertValidGeneralPlan(JSON.parse(serialized)); }
module.exports = { PLANNER_SCHEMA_VERSION, PLAN_STATUSES, buildInitialPlan, validateGeneralPlan, assertValidGeneralPlan, serializeGeneralPlan, deserializeGeneralPlan, normalizeStep, dedupeSteps, trace, planId };
