"use strict";
const crypto = require("crypto");
const { assessGoalSupport, candidateGoalTypes, profileForGoalType } = require("./supported_domains");
const INTENT_SCHEMA_VERSION = 1;
const INTENT_STATUSES = Object.freeze(["interpreted", "partially_interpreted", "clarification_required", "unsupported", "unsafe"]);
const GOAL_TYPES = Object.freeze(["file_change", "feature_addition", "bug_fix", "test_addition", "release", "documentation", "refactoring", "deployment", "external_operation", "abstract_improvement", "ambiguous"]);
const BAD_KEYS = new Set(["__proto__", "prototype", "constructor"]);
const ROOT_FIELDS = new Set(["schema_version","intent_id","raw_objective","normalized_objective","goal_type","actors","subject","desired_outcome","constraints","explicit_requirements","implicit_requirements","candidate_success_criteria","candidate_verifiers","assumptions","ambiguities","missing_information","confidence","confidence_by_field","risk_signals","external_dependencies","requested_scope","interpretation_status","candidate_interpretations","supported_domain","support_status","support_reasons","execution_boundary"]);
function plain(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const proto = Object.getPrototypeOf(value); return proto === Object.prototype || proto === null; }
function nonEmpty(value) { return typeof value === "string" && value.trim() !== ""; }
function clean(value) { if (!nonEmpty(value)) return ""; return String(value).replace(/-----BEGIN [^-]*PRIVATE KEY-----[\s\S]*?-----END [^-]*PRIVATE KEY-----/gi, "[REDACTED_PRIVATE_KEY]").replace(/\b(?:api[_ -]?key|access[_ -]?token|password|secret|credential)\s*(?:is|=|:)\s*[^\s,;]+/gi, "$1=[REDACTED]").replace(/\bBearer\s+[^\s]+/gi, "Bearer [REDACTED]").replace(/\s+/g, " ").trim(); }
function redact(value, key = "") { if (BAD_KEYS.has(key) || /token|secret|password|credential|api[_-]?key|authorization|private[_ -]?key/i.test(key)) return "[REDACTED]"; if (Array.isArray(value)) return value.map(item => redact(item)); if (plain(value)) return Object.fromEntries(Object.entries(value).map(([name, child]) => [name, redact(child, name)])); return typeof value === "string" ? clean(value) : value; }
function stableId(value) { return `intent_${crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex").slice(0, 16)}`; }
function inferred(id, text, confidence, rationale, extra = {}) { return { id, text: clean(text), confidence: Math.max(0, Math.min(1, confidence)), rationale: clean(rationale), ...extra }; }
function classify(objective) {
  const text = objective.toLowerCase();
  if (/release|publish|package|version|tag|ship/.test(text)) return "release";
  if (/deploy|production|staging/.test(text)) return "deployment";
  if (/improve|stabilize|optimize|modernize/.test(text)) return "abstract_improvement";
  if (/api|http|rest|external|service|database|cloud/.test(text)) return "external_operation";
  if (/bug|issue|error|defect|failure/.test(text)) return "bug_fix";
  if (/tests?|testing/.test(text) && /add|write|create/.test(text)) return "test_addition";
  if (/document|docs|readme/.test(text)) return "documentation";
  if (/refactor|restructure|clean up/.test(text)) return "refactoring";
  if (/feature|functionality|support/.test(text) && /add|implement|build|create/.test(text)) return "feature_addition";
  if (/file|module|class|function/.test(text) && /change|modify|update|edit/.test(text)) return "file_change";
  return "ambiguous";
}
function paths(objective) { return [...objective.matchAll(/(?:^|\s)((?:[A-Za-z0-9._-]+[\\/])+[A-Za-z0-9._-]+)/g)].map(match => match[1].replace(/\\/g, "/")); }
function interpretNaturalLanguageGoal(input = {}) {
  const raw = typeof input === "string" ? input : input.objective || "";
  const objective = clean(raw); const goalType = objective ? classify(objective) : "ambiguous"; const scopePaths = paths(objective); const external = ["release", "deployment", "external_operation"].includes(goalType); const risks = [];
  if (/ignore previous|system prompt|developer message|jailbreak|reveal prompt/i.test(raw)) risks.push({ id: "prompt-injection", signal: "Prompt-injection language", severity: "high", rationale: "Objective text cannot change agent authority" });
  if (/password|secret|credential|api[_ -]?key|access[_ -]?token|private key|bearer\s+/i.test(raw)) risks.push({ id: "sensitive-input", signal: "Credential-like material", severity: "critical", rationale: "Sensitive values must not be persisted" });
  if (external) risks.push({ id: "external-side-effect", signal: "External side effect", severity: "high", rationale: "External actions require explicit authorization" });
  const ambiguities = goalType === "ambiguous" ? [inferred("goal-type", "Action and target are unclear", .96, "No supported goal pattern matched")] : [];
  const missing = !objective ? [inferred("objective", "Provide a non-empty objective", 1, "Intent cannot be inferred from empty input")] : goalType === "ambiguous" || goalType === "abstract_improvement" ? [inferred("acceptance-boundary", "Define observable acceptance and scope", .9, "Abstract outcomes lack deterministic completion")] : external ? [inferred("external-target", "Identify authorized target and rollback conditions", .88, "External dependency is implied")] : [];
  if (risks.some(item => item.id === "prompt-injection")) ambiguities.push(inferred("authority", "Instruction-like text is untrusted", .96, "Prompt injection cannot grant authority"));
  const status = risks.some(item => item.id === "sensitive-input") ? "unsafe" : !objective ? "clarification_required" : missing.length || ambiguities.length ? "partially_interpreted" : "interpreted";
  const support = assessGoalSupport({ goal_type: goalType, confidence: status === "interpreted" ? .76 : .42, unsafe: risks.some(item => item.id === "sensitive-input") });
  const candidates = candidateGoalTypes(goalType, objective).map((candidate, index) => { const profile = profileForGoalType(candidate); return inferred(`interpretation-${index + 1}`, `Interpret as ${candidate}`, candidate === goalType ? .76 : Math.max(.35, .58 - index * .08), candidate === goalType ? "Primary classifier result" : "Alternative interpretation for clarification", { goal_type: candidate, supported_domain: profile.domain, execution_boundary: profile.execution_boundary, status: candidate === goalType ? "primary" : "candidate" }); });
  const inferredRequirements = [inferred("observable-outcome", "Outcome is observable after execution", .84, "Autonomous goals need evidence", { source: "inferred" })];
  if (!external) inferredRequirements.push(inferred("repository-scope", "Changes stay inside authorized workspace", .92, "Repository work respects ODD", { source: "inferred" }));
  const criteria = [inferred("outcome-observable", "Requested outcome is observable", .62, "Candidate only; not completion authority", { description: "Requested outcome is observable", required: true, observable: true, source: "inferred" })];
  const verifiers = [inferred("repository-observation", "Read-only repository observation", .52, "Observation is safer than assumption", { type: "custom", description: "Read-only repository observation", config: { paths: scopePaths } })];
  return createGoalIntent({ raw_objective: raw, normalized_objective: objective, goal_type: goalType, actors: [], subject: scopePaths.join(", ") || null, desired_outcome: inferred("desired-outcome", objective || "No objective", objective ? .72 : 0, "Normalized from user objective"), constraints: { scope: "authorized workspace and policy", external_access: external, production_access: goalType === "deployment", notes: [] }, explicit_requirements: objective ? [inferred("objective", objective, 1, "Copied from user input", { source: "explicit" })] : [], implicit_requirements: inferredRequirements, candidate_success_criteria: criteria, candidate_verifiers: verifiers, assumptions: [inferred("safe-default", "Use safe mode; intent never grants permission", .98, "Policy is independent")], ambiguities, missing_information: missing, confidence: status === "interpreted" ? .76 : .42, confidence_by_field: { goal_type: goalType === "ambiguous" ? .25 : .82, desired_outcome: objective ? .72 : 0, requested_scope: scopePaths.length ? .78 : .38 }, risk_signals: risks, external_dependencies: external ? [inferred("external-authorization", "Confirm authorized target", .94, "Intent cannot grant permission", { name: "Confirm authorized target", kind: "authorization", required: true })] : [], requested_scope: { paths: scopePaths, domains: [], resources: [], external, breadth: scopePaths.length ? "referenced_paths" : "unknown", rationale: scopePaths.length ? "Limited to explicit paths" : "No concrete scope" }, interpretation_status: status, candidate_interpretations: candidates, supported_domain: support.domain, support_status: support.status, support_reasons: support.reasons, execution_boundary: support.execution_boundary });
}
function createGoalIntent(input = {}) {
  if (!plain(input)) throw new TypeError("GoalIntent must be an object");
  const value = redact(input); const objective = clean(value.normalized_objective || value.raw_objective);
  return redact({ schema_version: 1, intent_id: stableId({ objective, type: value.goal_type || "ambiguous" }), raw_objective: typeof value.raw_objective === "string" ? value.raw_objective : objective, normalized_objective: objective, goal_type: value.goal_type || "ambiguous", actors: value.actors || [], subject: value.subject ?? null, desired_outcome: value.desired_outcome || inferred("desired-outcome", objective, .3, "Derived"), constraints: value.constraints || { scope: "authorized", external_access: false, production_access: false, notes: [] }, explicit_requirements: value.explicit_requirements || [], implicit_requirements: value.implicit_requirements || [], candidate_success_criteria: value.candidate_success_criteria || [], candidate_verifiers: value.candidate_verifiers || [], assumptions: value.assumptions || [], ambiguities: value.ambiguities || [], missing_information: value.missing_information || [], confidence: value.confidence ?? 0, confidence_by_field: value.confidence_by_field || {}, risk_signals: value.risk_signals || [], external_dependencies: value.external_dependencies || [], requested_scope: value.requested_scope || { paths: [], domains: [], resources: [], external: false, breadth: "unknown", rationale: "No scope" }, interpretation_status: value.interpretation_status || "clarification_required", candidate_interpretations: value.candidate_interpretations || [], supported_domain: value.supported_domain || profileForGoalType(value.goal_type || "ambiguous").domain, support_status: value.support_status || "clarification_required", support_reasons: value.support_reasons || [], execution_boundary: value.execution_boundary || "clarification_only" });
}
function hasBadKey(value) { if (Array.isArray(value)) return value.some(hasBadKey); if (!value || typeof value !== "object") return false; if (!plain(value)) return true; return Object.entries(value).some(([key, child]) => BAD_KEYS.has(key) || hasBadKey(child)); }
function validateIntent(value) {
  const errors = []; if (!plain(value)) return { valid: false, errors: [{ path: "$", code: "INVALID_OBJECT" }] };
  for (const key of Object.keys(value)) if (!ROOT_FIELDS.has(key)) errors.push({ path: key, code: BAD_KEYS.has(key) ? "DANGEROUS_FIELD" : "UNKNOWN_FIELD" });
  if (hasBadKey(value)) errors.push({ path: "$", code: "DANGEROUS_FIELD" }); if (value.schema_version !== INTENT_SCHEMA_VERSION) errors.push({ path: "schema_version", code: "INVALID_VERSION" }); if (!/^intent_[\da-f]{16}$/i.test(value.intent_id || "")) errors.push({ path: "intent_id", code: "INVALID_ID" }); if (!nonEmpty(value.normalized_objective) && value.interpretation_status !== "clarification_required") errors.push({ path: "normalized_objective", code: "INVALID_STRING" }); if (!GOAL_TYPES.includes(value.goal_type)) errors.push({ path: "goal_type", code: "INVALID_TYPE" }); if (!INTENT_STATUSES.includes(value.interpretation_status)) errors.push({ path: "interpretation_status", code: "INVALID_STATUS" });
  for (const key of ["actors", "explicit_requirements", "implicit_requirements", "candidate_success_criteria", "candidate_verifiers", "assumptions", "ambiguities", "missing_information", "risk_signals", "external_dependencies", "candidate_interpretations", "support_reasons"]) if (!Array.isArray(value[key])) errors.push({ path: key, code: "INVALID_LIST" }); if (!plain(value.desired_outcome) || !plain(value.constraints) || typeof value.constraints.external_access !== "boolean" || typeof value.constraints.production_access !== "boolean") errors.push({ path: "constraints", code: "INVALID_OBJECT" }); if (typeof value.confidence !== "number" || value.confidence < 0 || value.confidence > 1 || !plain(value.confidence_by_field)) errors.push({ path: "confidence", code: "INVALID_CONFIDENCE" }); if (!plain(value.requested_scope) || !Array.isArray(value.requested_scope.paths) || !Array.isArray(value.requested_scope.domains) || !Array.isArray(value.requested_scope.resources) || typeof value.requested_scope.external !== "boolean") errors.push({ path: "requested_scope", code: "INVALID_SCOPE" }); if (!["supported", "approval_required", "clarification_required", "unsupported"].includes(value.support_status)) errors.push({ path: "support_status", code: "INVALID_STATUS" }); if (!["local_bounded", "authorized_external", "clarification_only", "unsupported"].includes(value.execution_boundary)) errors.push({ path: "execution_boundary", code: "INVALID_BOUNDARY" }); if (typeof value.supported_domain !== "string" || !value.supported_domain.trim()) errors.push({ path: "supported_domain", code: "INVALID_DOMAIN" }); return { valid: errors.length === 0, errors };
}
function assertValidIntent(value) { const result = validateIntent(value); if (!result.valid) throw new TypeError(`Invalid GoalIntent: ${result.errors.map(item => item.path).join(",")}`); return value; }
function serializeIntent(value) { assertValidIntent(value); return JSON.stringify(redact(value)); }
function deserializeIntent(value) { return assertValidIntent(createGoalIntent(JSON.parse(value))); }
module.exports = { INTENT_SCHEMA_VERSION, INTENT_STATUSES, GOAL_TYPES, DANGEROUS_KEYS: BAD_KEYS, plain, redact, interpretNaturalLanguageGoal, createGoalIntent, validateIntent, assertValidIntent, serializeIntent, deserializeIntent };
