"use strict";

const crypto = require("crypto");
const path = require("path");
const { createCriterionEvidence, redactValue, redactText } = require("./evidence");

const VERIFIER_TYPES = Object.freeze(["file_state", "command", "test", "http_assertion", "process_health", "api_assertion", "database_read_only", "browser_assertion", "artifact_check", "git_state", "custom_adapter", "human_confirmation"]);
const VERIFIER_STATUSES = Object.freeze(["proposed", "validated", "invalid", "approval_required", "tampered"]);
const RESULT_STATUSES = Object.freeze(["passed", "failed", "unknown", "not_executed"]);
const SAFETY_CLASSES = Object.freeze(["read_only", "local_check", "external_read", "approval_required", "unsafe"]);
const BAD_KEYS = new Set(["__proto__", "prototype", "constructor"]);
const FIELDS = new Set(["schema_version", "verifier_id", "criterion_id", "type", "description", "inputs", "command_or_adapter", "expected_observation", "safety_class", "repeatable", "timeout_ms", "rollback_or_cleanup", "evidence_requirements", "confidence", "status", "verifier_fingerprint"]);
const COMMANDS = new Set(["npm", "npm.cmd", "node", "node.exe", "npx", "npx.cmd"]);
const SHELL_META = /[;&|<>`$()\n\r]/;
const NPM_READONLY = new Set(["test", "t", "run-script"]);
const NPM_SCRIPTS = new Set(["test", "lint", "typecheck", "check", "verify"]);
const UNSAFE_COMMAND = /(?:^|[\\/])\.\.(?:[\\/]|$)|(?:^|[\\/])(?:etc|proc|sys|dev)(?:[\\/]|$)|--(?:eval|exec|require|loader|inspect|prefix|global|location|registry|script-shell)/i;

function plain(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const proto = Object.getPrototypeOf(value); return proto === Object.prototype || proto === null; }
function text(value) { return typeof value === "string" && value.trim() !== ""; }
function issue(pathname, code, message) { return { path: pathname, code, message }; }
function hasBadKey(value) { if (Array.isArray(value)) return value.some(hasBadKey); if (!value || typeof value !== "object") return false; if (!plain(value)) return true; return Object.entries(value).some(([key, child]) => BAD_KEYS.has(key) || hasBadKey(child)); }
function unknownFields(value, pathname, errors) { if (!plain(value)) return; for (const key of Object.keys(value)) if (!FIELDS.has(key)) errors.push(issue(`${pathname}.${key}`, BAD_KEYS.has(key) ? "DANGEROUS_FIELD" : "UNKNOWN_FIELD", "Unknown or dangerous verifier field")); }
function stableId(prefix, value) { return `${prefix}_${crypto.createHash("sha256").update(JSON.stringify(redactValue(value))).digest("hex").slice(0, 16)}`; }
function verifierFingerprint(value) { const copy = { ...redactValue(value) }; delete copy.verifier_fingerprint; delete copy.status; return stableId("verifier", copy); }
function safePath(value, root = process.cwd()) { if (!text(value)) return { valid: false, reason: "path is required" }; const relative = path.relative(path.resolve(root), path.resolve(root, value)).replace(/\\/g, "/"); if (!relative || relative === ".." || relative.startsWith("../") || path.isAbsolute(relative) || relative.split("/").includes("..")) return { valid: false, reason: "path escapes workspace" }; return { valid: true, value: relative }; }
function commandValidation(value) {
  const config = value && typeof value === "object" ? value : {}; const command = typeof config.command === "string" ? path.basename(config.command).toLowerCase() : ""; const args = Array.isArray(config.args) ? config.args : null;
  if (!COMMANDS.has(command)) return { status: "invalid", reason: "command is outside the verifier allowlist" }; if (!args || args.some(item => typeof item !== "string")) return { status: "invalid", reason: "command args must be strings" }; if (SHELL_META.test(config.command) || args.some(item => SHELL_META.test(item))) return { status: "invalid", reason: "shell metacharacters are not allowed" }; if (args.some(item => UNSAFE_COMMAND.test(item))) return { status: "approval_required", reason: "command contains unsafe or side-effecting arguments" };
  if (command.startsWith("node")) return { status: args.length === 1 && ["--version", "-v", "--help", "-h"].includes(args[0]) ? "validated" : "invalid", reason: "node verifier only permits informational flags" };
  const subcommand = args.find(item => !item.startsWith("-"))?.toLowerCase(); if (!NPM_READONLY.has(subcommand)) return { status: "approval_required", reason: "npm verifier subcommand is not read-only" }; if (subcommand === "run-script" && !NPM_SCRIPTS.has(args[args.indexOf(subcommand) + 1])) return { status: "invalid", reason: "npm script is not allowlisted" }; return { status: "validated", reason: "command is allowlisted and read-only" };
}
function createDynamicVerifier(input = {}) {
  if (!plain(input)) throw new TypeError("Dynamic verifier must be a plain object");
  const value = redactValue(input); const verifier = { schema_version: 1, verifier_id: value.verifier_id || stableId("dynamic-verifier", value), criterion_id: value.criterion_id, type: value.type, description: value.description, inputs: plain(value.inputs) ? value.inputs : {}, command_or_adapter: value.command_or_adapter || null, expected_observation: value.expected_observation || {}, safety_class: value.safety_class || "read_only", repeatable: value.repeatable !== false, timeout_ms: Number.isSafeInteger(value.timeout_ms) && value.timeout_ms > 0 ? value.timeout_ms : 120000, rollback_or_cleanup: value.rollback_or_cleanup || null, evidence_requirements: Array.isArray(value.evidence_requirements) ? value.evidence_requirements : ["executed", "status", "observation"], confidence: typeof value.confidence === "number" ? value.confidence : 0.5, status: value.status || "proposed" };
  verifier.verifier_fingerprint = verifierFingerprint(verifier); return verifier;
}
function validateDynamicVerifier(value, options = {}) {
  const errors = []; if (!plain(value)) return { valid: false, errors: [issue("$", "INVALID_OBJECT", "Dynamic verifier must be a plain object")] }; unknownFields(value, "$", errors); if (hasBadKey(value)) errors.push(issue("$", "DANGEROUS_FIELD", "Dangerous nested key is not allowed"));
  if (value.schema_version !== 1) errors.push(issue("schema_version", "INVALID_VERSION", "Unsupported verifier schema version")); if (!/^dynamic-verifier_[A-Fa-f0-9]{16}$/.test(value.verifier_id || "")) errors.push(issue("verifier_id", "INVALID_ID", "Invalid verifier id")); if (!text(value.criterion_id) || !text(value.description)) errors.push(issue("description", "INVALID_STRING", "criterion_id and description are required")); if (!VERIFIER_TYPES.includes(value.type)) errors.push(issue("type", "INVALID_TYPE", "Unsupported verifier type")); if (!SAFETY_CLASSES.includes(value.safety_class)) errors.push(issue("safety_class", "INVALID_SAFETY_CLASS", "Unsupported verifier safety class")); if (typeof value.repeatable !== "boolean") errors.push(issue("repeatable", "INVALID_BOOLEAN", "repeatable must be boolean")); if (!Number.isSafeInteger(value.timeout_ms) || value.timeout_ms < 1 || value.timeout_ms > 2147483647) errors.push(issue("timeout_ms", "INVALID_TIMEOUT", "timeout_ms must be valid")); if (typeof value.confidence !== "number" || value.confidence < 0 || value.confidence > 1) errors.push(issue("confidence", "INVALID_CONFIDENCE", "confidence must be between 0 and 1")); if (!VERIFIER_STATUSES.includes(value.status)) errors.push(issue("status", "INVALID_STATUS", "Unsupported verifier status")); if (value.type === "command" || value.type === "test") { const result = commandValidation(value.command_or_adapter); if (result.status !== "validated") errors.push(issue("command_or_adapter", result.status === "approval_required" ? "APPROVAL_REQUIRED" : "INVALID_COMMAND", result.reason)); }
  if (value.type === "file_state") { const paths = Array.isArray(value.inputs?.paths) ? value.inputs.paths : []; if (!paths.length) errors.push(issue("inputs.paths", "INVALID_PATHS", "file_state requires paths")); for (const file of paths) { const checked = safePath(file, options.workspaceRoot); if (!checked.valid) errors.push(issue("inputs.paths", "INVALID_PATH", checked.reason)); } }
  if (value.safety_class === "unsafe") errors.push(issue("safety_class", "UNSAFE_VERIFIER", "Unsafe verifier cannot be executed")); if (value.verifier_fingerprint && value.verifier_fingerprint !== verifierFingerprint(value)) errors.push(issue("verifier_fingerprint", "VERIFIER_TAMPERING", "Verifier fingerprint mismatch")); return { valid: errors.length === 0, errors };
}
function assertValidDynamicVerifier(value, options = {}) { const result = validateDynamicVerifier(value, options); if (!result.valid) throw Object.assign(new TypeError(`Invalid dynamic verifier: ${result.errors.map(item => item.path).join(",")}`), { code: result.errors.some(item => item.code === "APPROVAL_REQUIRED") ? "APPROVAL_REQUIRED" : "INVALID_VERIFIER", errors: result.errors }); return value; }
function synthesizeVerifier(input = {}, context = {}) {
  const criterion = typeof input === "string" ? { id: "criterion", description: input } : input; const description = criterion.description || criterion.text || "Verify the requested outcome"; const paths = Array.isArray(context.paths) ? context.paths : [];
  const candidate = paths.length ? { criterion_id: criterion.id, type: "file_state", description: `Verify file state for: ${description}`, inputs: { paths }, expected_observation: { exists: true }, safety_class: "read_only", confidence: 0.72 } : /test|tests|regression/i.test(description) ? { criterion_id: criterion.id, type: "test", description: `Run an allowlisted repository test for: ${description}`, command_or_adapter: { command: "npm", args: ["test"] }, safety_class: "local_check", confidence: 0.62 } : { criterion_id: criterion.id, type: "human_confirmation", description: `Confirm the observable outcome: ${description}`, expected_observation: { confirmed: true }, safety_class: "approval_required", confidence: 0.4 };
  return createDynamicVerifier({ ...candidate, status: "proposed", evidence_requirements: ["executed", "status", "observation"] });
}
function normalizeResult(verifier, result = {}, options = {}) {
  const status = RESULT_STATUSES.includes(result.status) ? result.status : result.timed_out ? "unknown" : result.executed === false ? "not_executed" : result.success === true || result.passed === true ? "passed" : result.success === false || result.passed === false ? "failed" : "unknown";
  const valid = status === "passed" && result.executed === true && result.tampered !== true;
  return { status, valid, executed: result.executed === true, reason: redactText(result.reason || result.error || ""), observation: redactValue(result.observation || result.result || {}), evidence: createCriterionEvidence({ criterion_id: verifier.criterion_id, verifier_type: verifier.type, status, valid, executed: result.executed === true, execution: { executed: result.executed === true, duration_ms: result.duration_ms, exit_code: result.exit_code, timed_out: result.timed_out === true, error: result.error }, stdout: result.stdout, stderr: result.stderr, result: result.observation || result.result || {} }), timeout_ms: options.timeout_ms || verifier.timeout_ms };
}
function evaluateDynamicVerifier(verifier, options = {}) {
  const validation = validateDynamicVerifier(verifier, options); if (!validation.valid) return normalizeResult(verifier, { status: validation.errors.some(item => item.code === "APPROVAL_REQUIRED") ? "not_executed" : "unknown", reason: validation.errors.map(item => item.message).join("; "), executed: false });
  if (typeof options.observe !== "function") return normalizeResult(verifier, { status: "not_executed", reason: "injected verifier observer is required", executed: false });
  let timer;
  const timeout = new Promise(resolve => { timer = setTimeout(() => resolve({ status: "unknown", reason: "verifier timeout", timed_out: true, executed: true }), verifier.timeout_ms); });
  return Promise.race([Promise.resolve().then(() => options.observe(verifier)), timeout]).then(result => normalizeResult(verifier, result, options), error => normalizeResult(verifier, { status: "unknown", reason: error.message, executed: true })).finally(() => clearTimeout(timer));
}
function detectVerifierTampering(verifier, previousFingerprint) { const current = verifierFingerprint(verifier); return { tampered: Boolean(previousFingerprint && previousFingerprint !== current), previous_fingerprint: previousFingerprint || null, current_fingerprint: current }; }
function invalidateVerifierEvidence(evidence = [], verifier, reason = "verifier changed") { const tampered = detectVerifierTampering(verifier, verifier.verifier_fingerprint); return tampered.tampered ? evidence.map(item => ({ ...redactValue(item), valid: false, status: "unknown", invalidated: true, invalidation_reason: redactText(reason) })) : evidence; }
function resolveVerifierEvidence(results = []) { const values = results.filter(item => item && item.status !== "not_executed"); const passed = values.filter(item => item.status === "passed"); const failed = values.filter(item => item.status === "failed"); const conflict = passed.length > 0 && failed.length > 0; return { status: conflict ? "unknown" : passed.length && !failed.length ? "passed" : failed.length ? "failed" : "unknown", conflict, evidence: values.flatMap(item => item.evidence ? [item.evidence] : []) }; }
function isCompletionVerified(results = [], options = {}) { if (options.model_self_report === true) return false; const resolved = resolveVerifierEvidence(results); return resolved.status === "passed" && !resolved.conflict && results.every(item => item.status === "passed" && item.valid === true && item.evidence?.valid === true && item.evidence?.executed === true); }
module.exports = { VERIFIER_TYPES, VERIFIER_STATUSES, RESULT_STATUSES, SAFETY_CLASSES, commandValidation, safePath, createDynamicVerifier, validateDynamicVerifier, assertValidDynamicVerifier, synthesizeVerifier, normalizeResult, evaluateDynamicVerifier, detectVerifierTampering, invalidateVerifierEvidence, resolveVerifierEvidence, isCompletionVerified };


