"use strict";
const crypto = require("crypto");
const { redactValue } = require("./evidence");
const { expandGoalGeneral } = require("./expansion_general");
const { replan } = require("./replanner");
const { synthesizeVerifier, evaluateDynamicVerifier, isCompletionVerified } = require("./dynamic_verifier");
const { createBlockerReport, selectAlternative } = require("./blocker");
const LOOP_STATES = Object.freeze(["running", "paused", "completed", "blocked", "escalated", "timeout", "stagnated"]);
function array(value) { return Array.isArray(value) ? value : []; }
function stableId(prefix, value) { return `${prefix}_${crypto.createHash("sha256").update(JSON.stringify(redactValue(value))).digest("hex").slice(0, 16)}`; }
function now(options) { return (options.now || (() => new Date().toISOString()))(); }
function elapsed(started, current) { return Math.max(0, new Date(current).getTime() - new Date(started).getTime()); }
function tokenTotal(value = {}) { return (Number(value.input) || 0) + (Number(value.output) || 0); }
function append(history, type, detail) { return [...history, redactValue({ event_id: stableId("general-loop-event", { type, detail, index: history.length }), type, recorded_at: new Date().toISOString(), detail })]; }
function checkpoint(state, reason) { return redactValue({ checkpoint_id: stableId("general-checkpoint", { state, reason }), reason, state: state.state, plan_version: state.plan?.plan_version || null, current_step: state.current_step || null, action_history: state.action_history, evidence: state.evidence, saved_at: new Date().toISOString() }); }
function policyAllows(context = {}) { return context.mode !== "unrestricted_general" || context.explicit_confirmation === true || context.allow_general === true; }
function nextReadyStep(plan, completed = new Set(), failed = new Set()) { return array(plan?.steps).find(step => !completed.has(step.id) && !failed.has(step.id) && step.status !== "completed" && step.status !== "skipped" && array(step.depends_on).every(id => completed.has(id))) || null; }
function createInitialState(intent, options) { return { state: "running", objective: intent?.normalized_objective || intent?.raw_objective || "", plan: null, current_step: null, completed_steps: [], failed_steps: [], action_history: [], evidence: [], blocker_reports: [], alternative_history: [], replan_history: [], checkpoints: [], token_usage: { input: 0, output: 0 }, cycle_count: 0, started_at: now(options), updated_at: now(options), final_reason: null, terminal_resolution: null }; }

async function runGeneralGoalLoop(intent, options = {}) {
  const state = createInitialState(intent, options); const maxCycles = Number.isSafeInteger(options.max_cycles) ? options.max_cycles : 10; const timeoutMs = Number.isSafeInteger(options.timeout_ms) ? options.timeout_ms : 0; const maxTokens = Number.isSafeInteger(options.max_tokens) ? options.max_tokens : 0; const stagnationLimit = Number.isSafeInteger(options.stagnation_limit) ? options.stagnation_limit : 3; let noProgress = 0;
  if (!policyAllows(options)) return { ...state, state: "blocked", final_reason: "unrestricted_general requires explicit activation", checkpoints: [checkpoint(state, "policy_denied")] };
  const observe = typeof options.observeEnvironment === "function" ? options.observeEnvironment : async () => ({}); const plan = typeof options.plan === "function" ? options.plan : async input => expandGoalGeneral(intent, input.environment || {}); const execute = typeof options.execute === "function" ? options.execute : async step => ({ status: "not_executed", executed: false, reason: "injected executor is required", step_id: step.id }); const verify = typeof options.verify === "function" ? options.verify : async value => value; const replanFn = typeof options.replan === "function" ? options.replan : async (previous, input) => replan(previous, input);
  for (let cycle = 0; cycle < maxCycles; cycle += 1) {
    state.cycle_count = cycle + 1; state.updated_at = now(options); if (options.signal?.aborted || options.pause === true) { state.state = "paused"; state.final_reason = "user requested pause"; state.checkpoints.push(checkpoint(state, "paused_before_action")); return state; } if (timeoutMs && elapsed(state.started_at, state.updated_at) > timeoutMs) { state.state = "timeout"; state.final_reason = "timeout budget exceeded"; return state; } if (maxTokens && tokenTotal(state.token_usage) >= maxTokens) { state.state = "blocked"; state.final_reason = "token budget exceeded"; return state; }
    const environment = await observe({ cycle, intent, state: redactValue(state) }); state.action_history = append(state.action_history, "environment_observed", environment); const candidate = state.plan ? await replanFn(state.plan, { environment_changed: cycle > 0, completed_steps: state.completed_steps, failed_steps: state.failed_steps, evidence_ids: state.evidence.map(item => item.evidence_id) }) : await plan({ intent, environment, completed_steps: state.completed_steps, failed_steps: state.failed_steps }); state.plan = candidate.goal_plan || candidate.plan || candidate; state.action_history = append(state.action_history, cycle === 0 ? "plan_created" : "plan_replanned", { plan_version: state.plan?.plan_version || null, status: candidate.status });
    const selected = nextReadyStep(state.plan, new Set(state.completed_steps), new Set(state.failed_steps)); if (!selected) { const verification = await verify({ intent, plan: state.plan, evidence: state.evidence }); state.evidence.push(...array(verification?.evidence)); if (verification?.completed === true || isCompletionVerified(array(verification?.results), { model_self_report: verification?.model_self_report === true })) { state.state = "completed"; state.final_reason = "verified evidence completed the goal"; return state; } const lastBlocker = state.blocker_reports.at(-1); if (lastBlocker) state.terminal_resolution = redactValue({ blocker: lastBlocker, attempted_alternatives: lastBlocker.attempted_alternatives || state.alternative_history.map(item => item.alternative_id).filter(Boolean), recommended_alternative: lastBlocker.recommended_alternative || null, why_not_selected: state.alternative_history.at(-1)?.why_not_selected || [], required_external_action: lastBlocker.required_external_action || lastBlocker.terminal_reason?.required_external_action || null, resume_conditions: lastBlocker.resume_conditions || lastBlocker.terminal_reason?.resume_conditions || "Provide new verifier evidence and replan", next_user_action: lastBlocker.next_user_action || lastBlocker.terminal_reason?.next_user_action || "Review the blocker and choose an approved alternative" }); state.state = "escalated"; state.final_reason = "no executable verified step remains"; return state; }
    state.current_step = selected.id; const action = await execute(selected, { cycle, environment, plan: state.plan }); state.action_history = append(state.action_history, "step_executed", action); if (action?.tokens) { state.token_usage.input += Number(action.tokens.input) || 0; state.token_usage.output += Number(action.tokens.output) || 0; } const verifier = action?.verifier || synthesizeVerifier({ id: selected.target_criteria?.[0] || selected.id, description: selected.description }, { paths: selected.verification?.paths || [] }); const result = action?.verification || await evaluateDynamicVerifier(verifier, { observe: async () => verify({ intent, step: selected, action, environment }) }); state.evidence.push(result.evidence || result);
    if (result.status === "passed" && result.valid !== false) { state.completed_steps.push(selected.id); noProgress = 0; } else {
      state.failed_steps.push(selected.id); noProgress += 1;
      const blocker = createBlockerReport({ blocker_id: stableId("general-blocker", { step: selected.id, result }), affected_step: selected.id, category: result.category || (result.status === "unknown" ? "verification_failure" : undefined), cause: result.reason || action?.reason || action?.error || result.error || result.verification?.reason || result.status || "general loop action failed", stage: result.stage || action?.stage || "verify", evidence: [result.evidence].filter(Boolean), alternatives: result.alternatives || action?.alternatives, planner_alternatives: selected.alternatives || options.planner_alternatives, environment_alternatives: environment.alternatives || options.environment_alternatives, environment_workarounds: environment.workarounds || options.environment_workarounds, local_fallbacks: options.local_fallbacks, reduced_scope_alternatives: options.reduced_scope_alternatives, deferred_alternatives: options.deferred_alternatives, user_decision_alternatives: options.user_decision_alternatives, rollback_failure: result.rollback?.success === false || result.rollback_failure === true, required_external_action: result.required_external_action, resume_conditions: result.resume_conditions, next_user_action: result.next_user_action });
      state.blocker_reports.push(blocker);
      const selection = selectAlternative(blocker, { execution_policy: options.mode || options.execution_policy || "safe", explicit_confirmation: options.explicit_confirmation === true, auto_accept: options.auto_accept === true || options.autoAccept === true, actor: options.actor, config: options.config, runtime_permission: options.runtime_permission === true, audit_persisted: options.audit_persisted === true, integrity_preflight: options.integrity_preflight === true, used_alternative_ids: state.alternative_history.map(item => item.alternative_id).filter(Boolean), used_patch_signatures: state.action_history.map(item => item.detail?.patch_signature).filter(Boolean), used_external_targets: state.alternative_history.map(item => item.external_target).filter(Boolean), require_evidence: true });
      state.alternative_history.push(redactValue({ blocker_id: blocker.blocker_id, alternative_id: selection.alternative?.alternative_id || null, source: selection.alternative?.source || null, patch_signature: selection.alternative?.patch_signature || null, external_target: selection.alternative?.external_target || null, status: selection.status, reason: selection.reason, why_not_selected: selection.why_not_selected || [], approval_request: selection.approval_request || null, execution_status: selection.status === "selected" ? "scheduled" : selection.status, verification_status: "pending", evidence_complete: blocker.evidence_complete, rollback_failure: blocker.rollback_failure }));
      if (selection.status !== "selected") { state.state = "escalated"; state.terminal_resolution = redactValue({ blocker, attempted_alternatives: blocker.attempted_alternatives, recommended_alternative: blocker.recommended_alternative, why_not_selected: selection.why_not_selected || [], required_external_action: blocker.required_external_action || blocker.terminal_reason?.required_external_action || null, resume_conditions: blocker.resume_conditions || blocker.terminal_reason?.resume_conditions || null, next_user_action: blocker.next_user_action || blocker.terminal_reason?.next_user_action || "Review the blocker and choose an approved alternative" }); return state; }
      const nextPlan = await replanFn(state.plan, { blocker_reports: [blocker], selected_alternative: selection.alternative, verifier_failure: true, repeated_failure: noProgress > 1, stagnation: noProgress >= stagnationLimit, failed_steps: [selected.id], completed_steps: state.completed_steps, evidence_ids: state.evidence.map(item => item.evidence_id) }); state.replan_history.push(redactValue(nextPlan)); state.plan = nextPlan; if (noProgress >= stagnationLimit) { state.state = "stagnated"; state.final_reason = "stagnation limit exceeded"; return state; }
    }
  }
  state.state = "escalated"; state.final_reason = "maximum cycle limit exceeded"; return state;
}
module.exports = { LOOP_STATES, runGeneralGoalLoop, nextReadyStep, checkpoint };
