"use strict";

const crypto = require("crypto");
const { redactValue } = require("./evidence");
const { buildInitialPlan, normalizeStep, dedupeSteps, trace, validateGeneralPlan } = require("./general_planner");

const REPLAN_REASONS = Object.freeze(["environment_changed", "blocker", "verifier_failure", "assumption_invalidated", "dependency_unavailable", "external_state_mismatch", "user_feedback", "repeated_failure", "new_dependency", "stagnation", "tool_capability_changed", "manual"]);
function array(value) { return Array.isArray(value) ? value : []; }
function stableId(prefix, value) { return `${prefix}_${crypto.createHash("sha256").update(JSON.stringify(redactValue(value))).digest("hex").slice(0, 16)}`; }
function signature(value) { return stableId("patch", typeof value === "string" ? value : value?.patch || value?.description || value); }
function reasonFor(input = {}) { const reasons = []; if (input.environment_changed) reasons.push("environment_changed"); if (input.blocker_reports?.length) reasons.push("blocker"); if (input.verifier_failure) reasons.push("verifier_failure"); if (input.assumption_invalidated) reasons.push("assumption_invalidated"); if (input.dependency_unavailable) reasons.push("dependency_unavailable"); if (input.external_state_mismatch) reasons.push("external_state_mismatch"); if (input.user_feedback) reasons.push("user_feedback"); if (input.repeated_failure) reasons.push("repeated_failure"); if (input.new_dependency) reasons.push("new_dependency"); if (input.stagnation) reasons.push("stagnation"); if (input.tool_capability_changed) reasons.push("tool_capability_changed"); return reasons.length ? reasons : ["manual"]; }
function detectNoProgress(input = {}) { const completed = array(input.completed_steps); const prior = array(input.prior_completed_steps); const same = completed.length === prior.length && completed.every(item => prior.includes(item)); return { stagnant: input.stagnation === true || (same && (input.cycle_count || 0) > 0), reason: same ? "completed steps did not change" : "explicit stagnation signal" }; }
function relevantStep(step, objective) { const description = `${step.description || ""} ${step.purpose || ""}`.toLowerCase(); if (/unrelated|social media|social-media|marketing campaign|campaign/.test(description)) return false; const goal = String(objective || "").toLowerCase(); return !goal || description.split(/\s+/).some(word => word.length > 3 && goal.includes(word) || step.explicit_dependency === true || step.repair_strategy === true || step.source === "replan"); }
function replan(previousPlan, input = {}) {
  const prior = previousPlan || buildInitialPlan(input); const reasons = reasonFor(input); const completed = new Set(array(input.completed_steps)); const failed = new Set(array(input.failed_steps)); const rejected = new Set([...(prior.rejected_patch_signatures || []), ...array(input.failed_patch_signatures), ...array(input.failed_steps).map(signature)]); const noProgress = detectNoProgress(input); const full = reasons.includes("environment_changed") || reasons.includes("new_dependency") || reasons.includes("tool_capability_changed") || reasons.includes("stagnation");
  const preserved = prior.steps.filter(step => completed.has(step.id) || (!failed.has(step.id) && !full)); const discarded = prior.steps.filter(step => failed.has(step.id) || (full && !completed.has(step.id))); const proposed = array(input.new_steps).map(step => normalizeStep({ ...step, source: step.source || "replan" })).filter(step => !rejected.has(signature(step)) && relevantStep(step, prior.objective)); const steps = dedupeSteps([...preserved, ...proposed]); const version = prior.plan_version + 1; const next = steps.find(step => !completed.has(step.id) && !failed.has(step.id) && !rejected.has(signature(step)) && step.status !== "skipped")?.id || null; const status = noProgress.stagnant ? "blocked" : "replanning"; const result = buildInitialPlan({ ...prior, plan_id: stableId("general-plan", { prior: prior.plan_id, version }), plan_version: version, steps, preserved_steps: preserved.map(step => step.id), discarded_steps: discarded.map(step => step.id), new_steps: proposed.map(step => step.id), rejected_patch_signatures: [...rejected], replanning_reason: reasons.join(","), next_step: next, completed_steps: [...completed], status, planning_trace: [...array(prior.planning_trace), trace("plan_replanned", { reasons, full, preserved: preserved.map(step => step.id), discarded: discarded.map(step => step.id), new_steps: proposed.map(step => step.id) }, array(input.evidence_ids))] });
  const validation = validateGeneralPlan(result); return validation.valid ? result : { ...result, status: "blocked", validation_errors: validation.errors };
}
module.exports = { REPLAN_REASONS, signature, reasonFor, detectNoProgress, replan };
