"use strict";

const crypto = require("crypto");

const TOOL_REGISTRY_SCHEMA_VERSION = 1;
const TOOL_STATUSES = Object.freeze(["available", "unavailable", "approval_required", "stale", "blocked"]);
const BAD_KEYS = new Set(["__proto__", "prototype", "constructor"]);
const TOOL_FIELDS = new Set(["schema_version", "tool_id", "name", "kind", "description", "required_capabilities", "external", "adapter_injected", "status", "observed_at", "ttl_ms", "metadata", "evidence_id"]);
function plain(value) { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const proto = Object.getPrototypeOf(value); return proto === Object.prototype || proto === null; }
function text(value) { return typeof value === "string" && value.trim() !== ""; }
function redact(value, key = "") { if (BAD_KEYS.has(key) || /token|secret|password|credential|api[_-]?key|authorization|private[_ -]?key/i.test(key)) return "[REDACTED]"; if (Array.isArray(value)) return value.map(item => redact(item)); if (plain(value)) return Object.fromEntries(Object.entries(value).map(([name, child]) => [name, redact(child, name)])); return typeof value === "string" ? value.replace(/\s+/g, " ").trim() : value; }
function idFor(value) { return `tool_${crypto.createHash("sha256").update(JSON.stringify(redact(value))).digest("hex").slice(0, 16)}`; }
function createTool(input = {}) { if (!plain(input)) throw new TypeError("Tool must be a plain object"); return redact({ schema_version: 1, tool_id: input.tool_id || idFor(input), name: input.name, kind: input.kind || "unknown", description: input.description || "", required_capabilities: Array.isArray(input.required_capabilities) ? input.required_capabilities : [], external: input.external === true, adapter_injected: input.adapter_injected === true, status: input.status || "unavailable", observed_at: input.observed_at || new Date().toISOString(), ttl_ms: Number.isSafeInteger(input.ttl_ms) && input.ttl_ms > 0 ? input.ttl_ms : 60000, metadata: plain(input.metadata) ? input.metadata : {}, evidence_id: input.evidence_id || null }); }
function validateTool(value) { const errors = []; if (!plain(value)) return { valid: false, errors: [{ path: "$", code: "INVALID_OBJECT" }] }; for (const key of Object.keys(value)) if (!TOOL_FIELDS.has(key)) errors.push({ path: key, code: BAD_KEYS.has(key) ? "DANGEROUS_FIELD" : "UNKNOWN_FIELD" }); if (!/^tool_[A-Fa-f0-9]{16}$/.test(value.tool_id || "")) errors.push({ path: "tool_id", code: "INVALID_ID" }); if (!text(value.name)) errors.push({ path: "name", code: "INVALID_STRING" }); if (!Array.isArray(value.required_capabilities)) errors.push({ path: "required_capabilities", code: "INVALID_LIST" }); if (typeof value.external !== "boolean" || typeof value.adapter_injected !== "boolean") errors.push({ path: "tool", code: "INVALID_BOOLEAN" }); if (!TOOL_STATUSES.includes(value.status)) errors.push({ path: "status", code: "INVALID_STATUS" }); if (!Number.isSafeInteger(value.ttl_ms) || value.ttl_ms < 1) errors.push({ path: "ttl_ms", code: "INVALID_TTL" }); return { valid: errors.length === 0, errors }; }
function isStale(tool, now = Date.now()) { const observed = Date.parse(tool.observed_at); return !Number.isFinite(observed) || now - observed > tool.ttl_ms; }
function registerTool(registry, input) { const tools = Array.isArray(registry) ? registry.slice() : []; const tool = createTool({ ...input, status: isStale({ ...input, observed_at: input.observed_at || new Date().toISOString(), ttl_ms: input.ttl_ms || 60000 }) ? "stale" : input.status || "available" }); const existing = tools.findIndex(item => item.tool_id === tool.tool_id || item.name === tool.name); if (existing >= 0) tools[existing] = tool; else tools.push(tool); return tools; }
function discoverTools(definitions = [], context = {}) { return definitions.map(definition => registerTool([], { ...definition, status: definition.available === false ? "unavailable" : definition.external && context.external_capability !== true ? "approval_required" : definition.adapter_injected === false && definition.external ? "unavailable" : "available", observed_at: context.observed_at, evidence_id: context.evidence_id })[0]); }
function preflightTool(tool, context = {}) { const validation = validateTool(tool); if (!validation.valid) return { allowed: false, status: "blocked", reason: validation.errors.map(item => item.code).join(",") }; if (isStale(tool, context.now || Date.now())) return { allowed: false, status: "stale", reason: "tool observation is stale" }; if (tool.external && context.external_capability !== true) return { allowed: false, status: "approval_required", reason: "explicit external capability is required" }; const granted = new Set(Array.isArray(context.capabilities) ? context.capabilities : []); const missing = tool.required_capabilities.filter(capability => !granted.has(capability)); return missing.length ? { allowed: false, status: "approval_required", reason: "required capability is missing", missing_capabilities: missing } : { allowed: true, status: "available", reason: "tool preflight passed" }; }
module.exports = { TOOL_REGISTRY_SCHEMA_VERSION, TOOL_STATUSES, createTool, validateTool, isStale, registerTool, discoverTools, preflightTool, redact };
